### ISSUE TITLE
增加页面开头的 badge

### ISSUE THREAD

**Issue by LittleYe233** [LittleYe233/hexo-theme-amazingremake#5]
## 基本设想

考虑到一些页面可能一些醒目的 badge 来提醒读者（例如评价类文章的“spoiler”提醒），现提出增加针对于单个页面的配置项来实现这种元素。为保证灵活性，设想允许一部分内置 badge，并且其中一部分 badge 支持一些自定义的属性。未来可能可以增加对自定义 badge 的支持。

## 具体效果

例如，对于某个含有“剧透”提醒的文章，大体上可以以类似如下的形式呈现（转化为等价的 Markdown 表示）：

```markdown
# 测试文章标题

<div class="badge-[spoiler]">
剧透提醒 badge
</div>

## 测试段落标题

...
```

### 配置项

设想页面的 front-matter 中添加如下的配置项：

```yaml
...
badges:
- spoiler
- type: normal
  text: 这是一个常规 badge。
  foo: 这是 normal badge 的另一个自定义属性值。
...
```

这里的 `badges` 配置项为一个列表，其中可以为单个字符串（如 `spoiler`），表示默认配置或不可自定义配置的 badge；也可以为单个 object（如 `normal` badge），表示含有自定义配置的 badge。特别地，仅包含 `type` 属性值的 object 与单个字符串等效。对于不存在的 `type`，可以直接抛出警告，并忽略该项。

## 实现进度

- [ ] badge 系统
- [ ] 内置 badges
- [ ] 含有自定义配置项的内置 badges
- [ ] 用户预自定义的 badges
